import type { Spot } from '@/types/spot'

const BEACH_AMENITIES = [
  '주차장',
  '샤워장',
  '탈의실',
  '편의점',
  '화장실',
  '안전요원',
]
const VALLEY_AMENITIES = ['주차장', '화장실', '평상', '편의점']
const RIVER_AMENITIES = ['주차장', '래프팅 업체', '캠핑장', '화장실']
const MOUNTAIN_AMENITIES = ['주차장', '탐방안내소', '대피소', '매점']

export const MOCK_SPOTS: Spot[] = [
  // 바다 (해수욕장)
  {
    id: 'haeundae',
    name: '해운대해수욕장',
    type: 'beach',
    regionCode: 'gyeongsang',
    regionLabel: '부산',
    address: '부산 해운대구',
    description:
      '부산을 대표하는 최대 규모 해수욕장으로, 도심 접근성이 좋아 여름 내내 인파가 몰려요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 35.1587, lng: 129.1604 },
    basePopularity: 'severe',
    rating: 4.5,
    reviewCount: 18234,
    temperature: 29,
    tags: ['도심', '야경'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/34/3090534_image2_1.JPG',
  },
  {
    id: 'gyeongpo',
    name: '경포해수욕장',
    type: 'beach',
    regionCode: 'gangwon',
    regionLabel: '강릉',
    address: '강원 강릉시',
    description:
      '강릉 경포호와 인접한 백사장으로, 주변 카페거리와 함께 즐기기 좋아요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 37.8054, lng: 128.9066 },
    basePopularity: 'high',
    rating: 4.6,
    reviewCount: 12043,
    temperature: 27,
    tags: ['백사장', '카페거리'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/25/4075925_image2_1.jpg',
  },
  {
    id: 'daecheon',
    name: '대천해수욕장',
    type: 'beach',
    regionCode: 'chungcheong',
    regionLabel: '보령',
    address: '충남 보령시',
    description:
      '고운 모래와 갯벌이 함께 있어 매년 여름 보령머드축제가 열리는 곳이에요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 36.3225, lng: 126.5133 },
    basePopularity: 'medium',
    rating: 4.3,
    reviewCount: 9821,
    temperature: 28,
    tags: ['머드축제', '갯벌'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/66/3513866_image2_1.jpg',
  },
  {
    id: 'hyeopjae',
    name: '협재해수욕장',
    type: 'beach',
    regionCode: 'jeju',
    regionLabel: '제주',
    address: '제주 제주시',
    description:
      '에메랄드빛 바다와 비양도 전망이 어우러진 제주 대표 해변이에요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 33.3941, lng: 126.2397 },
    basePopularity: 'medium',
    rating: 4.8,
    reviewCount: 15672,
    temperature: 26,
    tags: ['에메랄드빛', '비양도뷰'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/66/3096066_image2_1.jpg',
  },
  {
    id: 'naksan',
    name: '낙산해수욕장',
    type: 'beach',
    regionCode: 'gangwon',
    regionLabel: '양양',
    address: '강원 양양군',
    description: '서핑과 일출 명소로 유명한 동해안 해변이에요.',
    amenities: [...BEACH_AMENITIES, '서핑용품 대여'],
    coordinates: { lat: 38.12, lng: 128.6275 },
    basePopularity: 'low',
    rating: 4.4,
    reviewCount: 7213,
    temperature: 25,
    tags: ['서핑', '일출'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/68/2929768_image2_1.jpg',
  },
  {
    id: 'eulwangri',
    name: '을왕리해수욕장',
    type: 'beach',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '인천',
    address: '인천 중구',
    description: '수도권에서 가장 가까운 서해 해수욕장으로 일몰이 아름다워요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 37.4485, lng: 126.3729 },
    basePopularity: 'high',
    rating: 4.1,
    reviewCount: 10982,
    temperature: 27,
    tags: ['근교', '일몰'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/78/3518478_image2_1.jpg',
  },
  {
    id: 'gwangalli',
    name: '광안리해수욕장',
    type: 'beach',
    regionCode: 'gyeongsang',
    regionLabel: '부산',
    address: '부산 수영구',
    description: '광안대교 야경과 함께 즐기는 부산의 인기 해변이에요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 35.1532, lng: 129.1187 },
    basePopularity: 'high',
    rating: 4.7,
    reviewCount: 20981,
    temperature: 29,
    tags: ['광안대교뷰', '펍거리'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/45/3311245_image2_1.jpg',
  },
  {
    id: 'hamdeok',
    name: '함덕해수욕장',
    type: 'beach',
    regionCode: 'jeju',
    regionLabel: '제주',
    address: '제주 제주시',
    description:
      '에메랄드빛 얕은 수심으로 가족 단위 물놀이에 적합한 제주 해변이에요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 33.5434, lng: 126.6697 },
    basePopularity: 'low',
    rating: 4.9,
    reviewCount: 13456,
    temperature: 26,
    tags: ['에메랄드빛', '가족여행'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/00/3354600_image2_1.jpg',
  },
  {
    id: 'anmyeon',
    name: '안면도해수욕장',
    type: 'beach',
    regionCode: 'chungcheong',
    regionLabel: '태안',
    address: '충남 태안군',
    description: '소나무 숲과 캠핑장이 함께 있어 힐링 여행지로 인기예요.',
    amenities: [...BEACH_AMENITIES, '캠핑장'],
    coordinates: { lat: 36.5333, lng: 126.3167 },
    basePopularity: 'low',
    rating: 4.2,
    reviewCount: 6521,
    temperature: 27,
    tags: ['소나무숲', '캠핑'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/17/3493617_image2_1.jpg',
  },
  {
    id: 'jeongdongjin',
    name: '정동진해수욕장',
    type: 'beach',
    regionCode: 'gangwon',
    regionLabel: '강릉',
    address: '강원 강릉시',
    description: '모래시계 공원과 기차역이 맞닿아 있는 일출 명소예요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 37.69, lng: 129.0333 },
    basePopularity: 'medium',
    rating: 4.5,
    reviewCount: 8934,
    temperature: 25,
    tags: ['일출명소', '기차역뷰'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/82/3534482_image2_1.jpg',
  },
  {
    id: 'mangsang',
    name: '망상해수욕장',
    type: 'beach',
    regionCode: 'gangwon',
    regionLabel: '동해',
    address: '강원 동해시',
    description: '오토캠핑장이 잘 갖춰져 있어 가족 단위 캠핑객이 즐겨 찾아요.',
    amenities: [...BEACH_AMENITIES, '오토캠핑장'],
    coordinates: { lat: 37.6167, lng: 129.0667 },
    basePopularity: 'low',
    rating: 4.3,
    reviewCount: 5210,
    temperature: 25,
    tags: ['오토캠핑', '한적함'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/20/3544320_image2_1.jpg',
  },
  {
    id: 'byeonsan',
    name: '변산해수욕장',
    type: 'beach',
    regionCode: 'jeolla',
    regionLabel: '부안',
    address: '전북 부안군',
    description: '채석강과 인접해 노을 감상하기 좋은 서해안 해변이에요.',
    amenities: BEACH_AMENITIES,
    coordinates: { lat: 35.6167, lng: 126.4833 },
    basePopularity: 'low',
    rating: 4.2,
    reviewCount: 4102,
    temperature: 28,
    tags: ['채석강', '노을'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/72/3446672_image2_1.jpg',
  },

  // 계곡
  {
    id: 'myeongji-valley',
    name: '명지계곡',
    type: 'valley',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '가평',
    address: '경기 가평군',
    description: '가평 대표 계곡으로 펜션이 밀집해 있어 접근성이 좋아요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 37.7833, lng: 127.4667 },
    basePopularity: 'high',
    rating: 4.4,
    reviewCount: 6820,
    temperature: 22,
    tags: ['물놀이', '펜션'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/03/3563403_image2_1.jpg',
  },
  {
    id: 'cheongpyeong-valley',
    name: '청평계곡',
    type: 'valley',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '가평',
    address: '경기 가평군',
    description: '수도권에서 가깝고 물놀이 시설이 잘 갖춰진 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 37.7333, lng: 127.4333 },
    basePopularity: 'high',
    rating: 4.2,
    reviewCount: 5124,
    temperature: 22,
    tags: ['근교', '물놀이'],
    imageUrl: 'https://picsum.photos/seed/cheongpyeong-valley/400/300',
  },
  {
    id: 'yongchu-valley',
    name: '용추계곡',
    type: 'valley',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '가평',
    address: '경기 가평군',
    description: '폭포와 트레킹 코스가 함께 있는 가평의 숨은 명소예요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 37.8667, lng: 127.4833 },
    basePopularity: 'medium',
    rating: 4.3,
    reviewCount: 3872,
    temperature: 21,
    tags: ['폭포', '트레킹'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/63/3077563_image2_1.jpg',
  },
  {
    id: 'baegun-valley',
    name: '백운계곡',
    type: 'valley',
    regionCode: 'gangwon',
    regionLabel: '홍천',
    address: '강원 홍천군',
    description:
      '1급수로 유명해 여름철 물놀이객이 많이 찾는 홍천의 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 37.85, lng: 128.0 },
    basePopularity: 'medium',
    rating: 4.6,
    reviewCount: 5432,
    temperature: 21,
    tags: ['1급수', '캠핑'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/97/3539797_image2_1.jpg',
  },
  {
    id: 'sipiseonnyeotang-valley',
    name: '십이선녀탕계곡',
    type: 'valley',
    regionCode: 'gangwon',
    regionLabel: '인제',
    address: '강원 인제군',
    description: '설악산 자락의 비경으로 손꼽히는 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 38.2, lng: 128.35 },
    basePopularity: 'medium',
    rating: 4.7,
    reviewCount: 4210,
    temperature: 20,
    tags: ['설악산', '비경'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/58/3042058_image2_1.jpg',
  },
  {
    id: 'osaek-valley',
    name: '오색계곡',
    type: 'valley',
    regionCode: 'gangwon',
    regionLabel: '양양',
    address: '강원 양양군',
    description: '설악산 오색약수와 이어지는 계곡으로 여름 피서객이 많아요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 38.1667, lng: 128.4667 },
    basePopularity: 'high',
    rating: 4.5,
    reviewCount: 6011,
    temperature: 21,
    tags: ['설악산', '약수'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/48/3387248_image2_1.JPG',
  },
  {
    id: 'bangtaesan-valley',
    name: '방태산계곡',
    type: 'valley',
    regionCode: 'gangwon',
    regionLabel: '인제',
    address: '강원 인제군',
    description: '원시림 속에 자리해 한적하게 즐기기 좋은 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 38.0833, lng: 128.3667 },
    basePopularity: 'low',
    rating: 4.6,
    reviewCount: 2310,
    temperature: 19,
    tags: ['원시림', '한적함'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/79/3357579_image2_1.jpg',
  },
  {
    id: 'woljeong-valley',
    name: '월정계곡',
    type: 'valley',
    regionCode: 'gangwon',
    regionLabel: '평창',
    address: '강원 평창군',
    description: '오대산 전나무숲길과 이어지는 청량한 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 37.7833, lng: 128.5833 },
    basePopularity: 'low',
    rating: 4.4,
    reviewCount: 2876,
    temperature: 20,
    tags: ['오대산', '전나무숲'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/54/3304054_image2_1.jpg',
  },
  {
    id: 'hwayang-valley',
    name: '화양계곡',
    type: 'valley',
    regionCode: 'chungcheong',
    regionLabel: '괴산',
    address: '충북 괴산군',
    description: '화양구곡의 아름다운 경관을 자랑하는 괴산의 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 36.7333, lng: 127.8667 },
    basePopularity: 'low',
    rating: 4.7,
    reviewCount: 4310,
    temperature: 22,
    tags: ['화양구곡', '경관'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/84/3059184_image2_1.jpg',
  },
  {
    id: 'daedunsan-valley',
    name: '대둔산계곡',
    type: 'valley',
    regionCode: 'jeolla',
    regionLabel: '완주',
    address: '전북 완주군',
    description: '케이블카와 함께 즐길 수 있는 완주의 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 36.1333, lng: 127.4 },
    basePopularity: 'medium',
    rating: 4.3,
    reviewCount: 3120,
    temperature: 21,
    tags: ['케이블카', '단풍'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/87/3396487_image2_1.JPG',
  },
  {
    id: 'gucheondong-valley',
    name: '구천동계곡',
    type: 'valley',
    regionCode: 'jeolla',
    regionLabel: '무주',
    address: '전북 무주군',
    description: '덕유산 구천동 33경으로 잘 알려진 무주의 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 35.85, lng: 127.6833 },
    basePopularity: 'medium',
    rating: 4.5,
    reviewCount: 5901,
    temperature: 21,
    tags: ['덕유산', '33경'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/75/3536275_image2_1.jpg',
  },
  {
    id: 'baemsagol-valley',
    name: '뱀사골계곡',
    type: 'valley',
    regionCode: 'jeolla',
    regionLabel: '남원',
    address: '전북 남원시',
    description: '지리산 국립공원 내 위치한 단풍과 계곡물이 아름다운 곳이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 35.4167, lng: 127.5833 },
    basePopularity: 'low',
    rating: 4.6,
    reviewCount: 3872,
    temperature: 20,
    tags: ['지리산', '단풍명소'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/53/3517053_image2_1.jpg',
  },
  {
    id: 'piagol-valley',
    name: '피아골계곡',
    type: 'valley',
    regionCode: 'jeolla',
    regionLabel: '구례',
    address: '전남 구례군',
    description: '지리산 자락의 단풍 명소이자 여름 피서지예요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 35.3, lng: 127.6333 },
    basePopularity: 'low',
    rating: 4.5,
    reviewCount: 2543,
    temperature: 20,
    tags: ['지리산', '단풍'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/32/3574832_image2_1.jpg',
  },
  {
    id: 'ssanggyesa-valley',
    name: '쌍계사계곡',
    type: 'valley',
    regionCode: 'gyeongsang',
    regionLabel: '하동',
    address: '경남 하동군',
    description: '십리벚꽃길과 이어지는 하동의 대표 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 35.2333, lng: 127.6833 },
    basePopularity: 'medium',
    rating: 4.5,
    reviewCount: 4567,
    temperature: 22,
    tags: ['지리산', '벚꽃길'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/55/4075655_image2_1.jpg',
  },
  {
    id: 'deoksan-valley',
    name: '덕산계곡',
    type: 'valley',
    regionCode: 'gyeongsang',
    regionLabel: '산청',
    address: '경남 산청군',
    description: '지리산 자락 산청에 위치한 한적한 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 35.35, lng: 127.85 },
    basePopularity: 'low',
    rating: 4.4,
    reviewCount: 2109,
    temperature: 21,
    tags: ['지리산', '한적함'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/95/3364095_image2_1.JPG',
  },
  {
    id: 'ssangyong-valley',
    name: '쌍룡계곡',
    type: 'valley',
    regionCode: 'gyeongsang',
    regionLabel: '문경',
    address: '경북 문경시',
    description: '백두대간을 따라 흐르는 문경의 캠핑 명소예요.',
    amenities: [...VALLEY_AMENITIES, '캠핑장'],
    coordinates: { lat: 36.7833, lng: 128.0667 },
    basePopularity: 'low',
    rating: 4.3,
    reviewCount: 1876,
    temperature: 21,
    tags: ['백두대간', '캠핑'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/21/3049821_image2_1.JPG',
  },
  {
    id: 'juwangsan-valley',
    name: '주왕산계곡',
    type: 'valley',
    regionCode: 'gyeongsang',
    regionLabel: '청송',
    address: '경북 청송군',
    description: '기암절벽으로 유명한 주왕산 국립공원 내 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 36.3833, lng: 129.1833 },
    basePopularity: 'low',
    rating: 4.4,
    reviewCount: 2984,
    temperature: 21,
    tags: ['국립공원', '기암절벽'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/06/3474106_image2_1.jpg',
  },
  {
    id: 'donnaeko-valley',
    name: '돈내코계곡',
    type: 'valley',
    regionCode: 'jeju',
    regionLabel: '서귀포',
    address: '제주 서귀포시',
    description:
      '원앙폭포로 이어지는 숲길이 아름다운 제주 서귀포의 계곡이에요.',
    amenities: VALLEY_AMENITIES,
    coordinates: { lat: 33.2667, lng: 126.6167 },
    basePopularity: 'medium',
    rating: 4.3,
    reviewCount: 3215,
    temperature: 23,
    tags: ['원앙폭포', '숲길'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/84/3589084_image2_1.jpg',
  },

  // 하천·강
  {
    id: 'hantan-river',
    name: '한탄강',
    type: 'river',
    regionCode: 'gangwon',
    regionLabel: '철원',
    address: '강원 철원군',
    description: '주상절리 절경과 함께 래프팅을 즐길 수 있는 철원의 강이에요.',
    amenities: RIVER_AMENITIES,
    coordinates: { lat: 38.2667, lng: 127.3 },
    basePopularity: 'medium',
    rating: 4.5,
    reviewCount: 4521,
    temperature: 23,
    tags: ['래프팅', '주상절리'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/68/2616468_image2_1.bmp',
  },
  {
    id: 'naerincheon-river',
    name: '내린천',
    type: 'river',
    regionCode: 'gangwon',
    regionLabel: '인제',
    address: '강원 인제군',
    description: '국내 대표 래프팅 명소로 급류가 매력적인 인제의 하천이에요.',
    amenities: RIVER_AMENITIES,
    coordinates: { lat: 37.9667, lng: 128.3 },
    basePopularity: 'high',
    rating: 4.6,
    reviewCount: 5230,
    temperature: 22,
    tags: ['래프팅', '급류'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/66/2616266_image2_1.bmp',
  },
  {
    id: 'donggang-river',
    name: '동강',
    type: 'river',
    regionCode: 'gangwon',
    regionLabel: '영월',
    address: '강원 영월군',
    description: '수려한 비경으로 유명한 영월의 래프팅 명소예요.',
    amenities: RIVER_AMENITIES,
    coordinates: { lat: 37.1667, lng: 128.4667 },
    basePopularity: 'medium',
    rating: 4.7,
    reviewCount: 3892,
    temperature: 23,
    tags: ['래프팅', '비경'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/54/3493254_image2_1.jpg',
  },
  {
    id: 'hongcheongang-river',
    name: '홍천강',
    type: 'river',
    regionCode: 'gangwon',
    regionLabel: '홍천',
    address: '강원 홍천군',
    description: '수도권 근교 물놀이와 캠핑으로 인기 있는 하천이에요.',
    amenities: RIVER_AMENITIES,
    coordinates: { lat: 37.7, lng: 127.7667 },
    basePopularity: 'high',
    rating: 4.3,
    reviewCount: 4980,
    temperature: 24,
    tags: ['물놀이', '캠핑'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/63/3584663_image2_1.jpg',
  },
  {
    id: 'paldang-river',
    name: '팔당한강공원',
    type: 'river',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '남양주',
    address: '경기 남양주시',
    description: '한강 자전거길과 이어지는 수도권 근교 물놀이 명소예요.',
    amenities: [...RIVER_AMENITIES, '자전거 대여소'],
    coordinates: { lat: 37.5333, lng: 127.25 },
    basePopularity: 'high',
    rating: 4.0,
    reviewCount: 3456,
    temperature: 25,
    tags: ['근교', '자전거길'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/94/3507294_image2_1.jpg',
  },
  {
    id: 'pyeongchanggang-river',
    name: '평창강',
    type: 'river',
    regionCode: 'gangwon',
    regionLabel: '평창',
    address: '강원 평창군',
    description: '한적하게 캠핑과 물놀이를 즐기기 좋은 강이에요.',
    amenities: RIVER_AMENITIES,
    coordinates: { lat: 37.3667, lng: 128.3833 },
    basePopularity: 'low',
    rating: 4.4,
    reviewCount: 1987,
    temperature: 22,
    tags: ['캠핑', '한적함'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/82/3569682_image2_1.jpg',
  },
  {
    id: 'seomjingang-river',
    name: '섬진강',
    type: 'river',
    regionCode: 'jeolla',
    regionLabel: '구례',
    address: '전남 구례군',
    description: '벚꽃길로도 유명한 구례의 자전거길 옆 강이에요.',
    amenities: [...RIVER_AMENITIES, '자전거 대여소'],
    coordinates: { lat: 35.2, lng: 127.4667 },
    basePopularity: 'low',
    rating: 4.5,
    reviewCount: 2765,
    temperature: 24,
    tags: ['자전거길', '벚꽃'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/90/4064090_image2_1.jpg',
  },

  // 산
  {
    id: 'seoraksan',
    name: '설악산',
    type: 'mountain',
    regionCode: 'gangwon',
    regionLabel: '속초',
    address: '강원 속초시',
    description: '케이블카와 단풍으로 유명한 대한민국 대표 국립공원이에요.',
    amenities: [...MOUNTAIN_AMENITIES, '케이블카'],
    coordinates: { lat: 38.1197, lng: 128.465 },
    basePopularity: 'high',
    rating: 4.8,
    reviewCount: 15234,
    temperature: 20,
    tags: ['국립공원', '케이블카'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/36/3564436_image2_1.jpg',
  },
  {
    id: 'jirisan',
    name: '지리산',
    type: 'mountain',
    regionCode: 'gyeongsang',
    regionLabel: '하동',
    address: '경남 하동군',
    description: '종주 코스로 유명한 국내 최대 규모의 국립공원이에요.',
    amenities: MOUNTAIN_AMENITIES,
    coordinates: { lat: 35.3378, lng: 127.7306 },
    basePopularity: 'medium',
    rating: 4.7,
    reviewCount: 9821,
    temperature: 19,
    tags: ['국립공원', '종주'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/65/3049765_image2_1.JPG',
  },
  {
    id: 'hallasan',
    name: '한라산',
    type: 'mountain',
    regionCode: 'jeju',
    regionLabel: '제주',
    address: '제주 제주시',
    description: '백록담을 품은 제주의 상징적인 산이에요.',
    amenities: MOUNTAIN_AMENITIES,
    coordinates: { lat: 33.3617, lng: 126.5292 },
    basePopularity: 'high',
    rating: 4.9,
    reviewCount: 12456,
    temperature: 18,
    tags: ['국립공원', '백록담'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/41/3460441_image2_1.jpg',
  },
  {
    id: 'bukhansan',
    name: '북한산',
    type: 'mountain',
    regionCode: 'seoul-incheon-gyeonggi',
    regionLabel: '서울',
    address: '서울 강북구',
    description: '서울 도심에서 가까워 접근성이 좋은 암벽 등반 명소예요.',
    amenities: MOUNTAIN_AMENITIES,
    coordinates: { lat: 37.6585, lng: 126.977 },
    basePopularity: 'severe',
    rating: 4.4,
    reviewCount: 20123,
    temperature: 24,
    tags: ['도심근교', '암벽'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/83/2795083_image2_1.jpeg',
  },
  {
    id: 'odaesan',
    name: '오대산',
    type: 'mountain',
    regionCode: 'gangwon',
    regionLabel: '평창',
    address: '강원 평창군',
    description: '전나무숲길과 사찰이 어우러진 평창의 국립공원이에요.',
    amenities: MOUNTAIN_AMENITIES,
    coordinates: { lat: 37.7981, lng: 128.5497 },
    basePopularity: 'low',
    rating: 4.6,
    reviewCount: 4321,
    temperature: 19,
    tags: ['전나무숲', '사찰'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource_photo/60/3569060_image2_1.jpg',
  },
  {
    id: 'gyeryongsan',
    name: '계룡산',
    type: 'mountain',
    regionCode: 'chungcheong',
    regionLabel: '공주',
    address: '충남 공주시',
    description: '사찰과 능선 산행으로 유명한 공주의 국립공원이에요.',
    amenities: MOUNTAIN_AMENITIES,
    coordinates: { lat: 36.3564, lng: 127.2119 },
    basePopularity: 'medium',
    rating: 4.3,
    reviewCount: 3654,
    temperature: 23,
    tags: ['국립공원', '사찰'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/73/3509273_image2_1.jpg',
  },
  {
    id: 'deogyusan',
    name: '덕유산',
    type: 'mountain',
    regionCode: 'jeolla',
    regionLabel: '무주',
    address: '전북 무주군',
    description: '곤돌라로 정상까지 오를 수 있는 무주의 고원 산이에요.',
    amenities: [...MOUNTAIN_AMENITIES, '곤돌라'],
    coordinates: { lat: 35.8617, lng: 127.7503 },
    basePopularity: 'low',
    rating: 4.5,
    reviewCount: 3012,
    temperature: 20,
    tags: ['곤돌라', '고원'],
    imageUrl:
      'https://tong.visitkorea.or.kr/cms/resource/42/3064442_image2_1.JPG',
  },
]
